version: '{build}'

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    platform: x64
    qt: 5.14
    releaseName: NDR_Client_5.14_x64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    platform: x64
    qt: 5.13
    releaseName: NDR_Client_5.14_x64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    platform: x64
    qt: 5.12
    releaseName: NDR_Client_5.14_x64

install:
  - set QTDIR=C:\Qt\%qt%\mingw73_64
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw730_64\bin;%PATH%

build_script:
  - mkdir build && cd build
  - qmake -config release ../ndr-client.pro
  - mingw32-make -j %NUMBER_OF_PROCESSORS%
  - cd ..
  - 7z a NDR_Client_%qt%_%platform%.zip .\build\*

artifacts:
  - path: NDR_Client_%qt%_%platform%.zip

